[target.'cfg(all(target_arch = "{{ arch }}", target_os = "none"))']
runner = "probe-run --chip {{ probe_chip }}"
rustflags = [
  # Code-size optimizations.
  "-Z", "trap-unreachable=no",
  "-C", "inline-threshold=5",
  "-C", "no-vectorize-loops",
]

[build]
target = "{{ rust_target }}"

[env]
DEFMT_LOG = "info"
